title: Haxing with Brent
author: Brent Butler
email: bcbutler35@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Join me as a work my way through various challenges. Becoming a world class hacker is #1 on my list!
# social links
twitter_username: _bcbutler # DO NOT include the @ character, or else the build will fail!
github_username:  butlerbc # DO NOT include the @ character, or else the build will fail!

show_excerpts: false  # set to false to remove excerpts on the homepage
theme: minima
